*Authors:* 

In [ ]:
# Needed in all problems
import numpy as np

## Problems

### Problem 1:

Write a function `slicer_10(in_array)` where `in_array` is guaranteed to be of length 10.
Return three slices of `in_array` such that they contain:

- slice 1: the last 5 elements
- slice 2: the central 4 elements
- slice 3: every odd-indexed elements

Return the slices in the same order as listed above.

In [ ]:
# PROBLEM (1)


# SOLUTION
def slicer_10(in_array):
    slice1 = in_array[-5:]
    slice2 = in_array[3:7]
    slice3 = in_array[[1,3,5,7,9]]
    return slice1, slice2, slice3

# PROBLEM-TEST
my_array = np.arange(10)
slice1, slice2, slice3 = slicer_10(my_array)
slice1.tolist(), slice2.tolist(), slice3.tolist()

In [ ]:
# SELF-CHECK
# should be (array([4, 3, 2, 1, 0]), array([6, 5, 4, 3]), array([8, 6, 4, 2, 0]))
arange_array = np.arange(start=9, stop=-1, step=-1)
slice1, slice2, slice3 = slicer_10(arange_array)
slice1, slice2, slice3

### Problem 2:

Write a function `fancy_array_filter` that takes one multidimensional array as parameter.
The output should be a tuple that contains the following arrays in this order:
- a flat array that contains only values of the input array that are exclusively between 6 and 30
- a flat array that contains only values of the input array that are divisible by 2 but are not divisible by 3
- the input array where you added 25 to all values that are divisible by 2 but are not divisible by 3 and are not negative

Use array operations to achieve this.
Keep the order intact, for the two flat arrays the order of the elements should be the same as in a flattened version of the input array.

In [ ]:
# PROBLEM (1)


# SOLUTION
def fancy_array_filter(in_array):
    out = in_array[(in_array > 6) & (in_array < 30)]
    out2 = in_array[(in_array % 3 != 0) & (in_array % 2 == 0)]
    in_array[(in_array % 3 != 0) & (in_array % 2 == 0) & (in_array > 0)] += 25
    return out, out2, in_array

# PROBLEM-TEST
my_array = np.arange(-12, 42, 1).reshape(3, 3, 6)
out, out2, my_array = fancy_array_filter(my_array)
out.tolist(), out2.tolist(), my_array.tolist()

In [ ]:
# SELF-CHECK
# the result should be:
# (array([ 8, 12,  9, 10, 12, 13, 14,  9,  8, 15,  7, 20, 10]),
#  array([ 8, 10,  4, 14,  2, -4,  8,  2, 20, 10,  2]),
#  array([[  5,  33,  12],
#         [  3,   5,   6],
#         [  9,  35,  29],
#         [  1,   0,   1],
#         [ 12,  13,  39],
#         [  0,   9,  27],
#         [ -4,   6,  33],
#         [ -7,  15,   3],
#         [ 27,   3,   3],
#         [  5,   6,   7],
#         [ -6,  45,  35],
#         [ 42, -12,  27]]))
matrix1 = np.array([
    [5, 8, 12],
    [3, 5, 6],
    [9, 10, 4],
    [1, 0, 1],
    [12, 13, 14],
    [0, 9, 2],
    [-4, 6, 8],
    [-7, 15, 3],
    [2, 3, 3],
    [5, 6, 7],
    [-6, 20, 10],
    [42, -12, 2],
])
fancy_array_filter(matrix1)

### Problem 3:

Write a function `exam_statistics` with one parameter that is guaranteed to be a 2D NumPy array.
Consider this array representing the scores of students in a class in several exams.
Each row represents a student and each column represents an exam.
The entries represent the score the corresponding student reached in the corresponding exam.
An example of such an array can be seen in the `# SELF-CHECK` cell.
The function should return a tuple containing the following things in this order:
1. mean student: An array containing the mean score for each student (row-wise, 2nd dimension).
2. mean exam: An array containing the mean score for each exam (column-wise, 1st dimension).
3. mean overall: The overall mean score for the entire dataset.
4. max overall: Find the highest score in the dataset.


In [ ]:
# PROBLEM (2)

# SOLUTION
def exam_statistics(scores):
    mean_student = np.mean(scores, axis=1)
    mean_exam = np.mean(scores, axis=0)
    mean_overall = np.mean(scores)
    max_overall = np.max(scores)
    return mean_student, mean_exam, mean_overall, max_overall

# PROBLEM-TEST
scores = np.array([[90, 100, 98, 93, 96],
                   [55, 72, 64, 59, 80],
                   [88, 88, 88, 88, 88],
                   [78, 84, 90, 91, 73]])
mean_student, mean_exam, mean_overall, max_overall = exam_statistics(scores)
np.around(mean_student, 1).tolist(), np.around(mean_exam, 1).tolist(), round(mean_overall, 1).tolist(), max_overall.tolist()

In [ ]:
# SELF-CHECK
# should be
# (array([78.75, 87.25, 68.75, 74.25, 82.25]),
#  array([76.8, 75.8, 86. , 74.4]),
#  78.25,
#  95)

                  # ex1 ex2 ex3 ex4
scores = np.array([[80, 70, 90, 75],  # student 1
                   [95, 85, 89, 80],  # student 2
                   [60, 78, 70, 67],  # student 3
                   [61, 79, 89, 68],  # student 4
                   [88, 67, 92, 82]]) # student 5

exam_statistics(scores)

### Problem 4:

Write a function `matrix_calculator(matrix_a, matrix_b)` where `matrix_a` and `matrix_b` are 2D NumPy arrays with the same shape and quadratic (guaranteed).
The function should perform the following operations using NumPy functions and return a tuple containing the results in the following order:

1. scalar product: Multiply `matrix_a` by a scalar value of 3.
2. element-wise product: Compute the element-wise product (Hadamard product) of `matrix_a` and `matrix_b`.
3. dot product: Compute the matrix multiplication (dot product) of `matrix_a` and `matrix_b`.

In [ ]:
# PROBLEM (2)

# SOLUTION
def matrix_calculator(matrix_a, matrix_b):
    scalar_prod = matrix_a * 3
    element_prod = matrix_a * matrix_b
    dot_prod = matrix_a @ matrix_b
    return scalar_prod, element_prod, dot_prod

# PROBLEM-TEST
matrix_a = np.array([
    [2, 4, 6],
    [3, 1, 5],
    [7, 9, 11],
])

matrix_b = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
])

scalar_prod, element_prod, dot_prod = matrix_calculator(matrix_a, matrix_b)
scalar_prod.flatten().tolist(), np.diag(element_prod).tolist(), dot_prod.flatten().tolist()

In [ ]:
# SELF-CHECK
# should be
# (array([[12, 27, 18],
#         [15,  3,  9],
#         [21, 12, 24]]),
#  array([[4, 0, 0],
#         [5, 1, 0],
#         [7, 4, 8]]),
#  array([[19, 15,  6],
#         [ 9,  4,  3],
#         [19, 12,  8]]))

matrix_a = np.array([
    [4, 9, 6],
    [5, 1, 3],
    [7, 4, 8],
])
matrix_b = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [1, 1, 1],
])

matrix_calculator(matrix_a, matrix_b)

### Problem 5:

A spaceship sits motionless (relative to the sun) in our solar system, (where the x-direction is orthogonal to the orbital plane of the earth).
Write a function `spaceship_navigation` that gets the initial orientation as the first parameter.
The second parameter is a list of navigation commands.
Each command is a tuple containing a rotation in degree and the axis.

For example: the initial orientation is (1, 0, 0) and in order to adjust its course, the ship performs a series of rotations:
- $25^{\circ}$ rotation around the y-axis
- $75^{\circ}$ rotation around the x-axis
- $-10^{\circ}$ rotation around the z-axis

The corresponding initial orientation and list of commands would look like:
```python
orientation0 = np.array([1, 0, 0])
commands = [(25, 'y'), (75, 'x'), (-10, 'z')]
```

Calculate the orientation of the ship after each of the subsequent rotations.
Return a list containing all (intermediate) orientations. Remember that the result of each intermediate rotation is the initial orientation for the next rotation.

**Hint**: 3D Rotation matrices are defined as:
$$R_{x}(\theta) = \begin{bmatrix}
1 & 0 & 0\\
0 & \cos{\theta} & -\sin{\theta}\\
0 & \sin{\theta} & \cos{\theta}
\end{bmatrix}$$

$$R_{y}(\theta) = \begin{bmatrix}
\cos{\theta} & 0 & \sin{\theta}\\
0 & 1 & 0\\
-\sin{\theta} & 0 & \cos{\theta}
\end{bmatrix}$$

$$R_{z}(\theta) = \begin{bmatrix}
\cos{\theta} & -\sin{\theta} & 0\\
\sin{\theta} & \cos{\theta} & 0\\
0 & 0 & 1
\end{bmatrix}$$

You can write helper functions to multiply a vector with these matrices, taking the angle as an additional parameter.

**Hint**: Both NumPy and math have built-in trigonometric functions. You can check the respective documentation for details and whether they use radians or degrees as their respective inputs. 


In [ ]:
# PROBLEM (3)

# SOLUTION

def R_x(vect, theta):
    rot = [
        [1, 0, 0],
        [0, np.cos(theta), -np.sin(theta)],
        [0, np.sin(theta), np.cos(theta)],
    ]
    return rot @ vect

def R_y(vect, theta):
    rot = [
        [np.cos(theta), 0, np.sin(theta)],
        [0, 1, 0],
        [-np.sin(theta), 0, np.cos(theta)],
    ]
    return rot @ vect

def R_z(vect, theta):
    rot = [
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1],
    ]
    return rot @ vect

def spaceship_navigation(orientation0, commands):
    orientation = orientation0
    orientations = []
    for angle, axis in commands:
        if axis == 'x':
            orientation = R_x(orientation, np.radians(angle))
        elif axis == 'y':
            orientation = R_y(orientation, np.radians(angle))
        elif axis == 'z':
            orientation = R_z(orientation, np.radians(angle))
        orientations.append(orientation)
    return orientations


# PROBLEM-TEST
orientation0 = np.array([0, 0, 1])
commands = [(90, 'z'), (-20, 'y'), (30, 'x'), (20, 'x'), (45, 'z')]
orientation1, orientation12, orientation123, orientation1234, orientation12345 = spaceship_navigation(orientation0, commands)
np.around(orientation1, 2).tolist(), np.around(orientation12, 2).tolist(), np.around(orientation123, 2).tolist(), np.around(orientation1234, 2).tolist(), np.around(orientation12345, 2).tolist()

In [ ]:
# SELF-CHECK
# should be
# [array([ 0.90630779,  0.        , -0.42261826]),
#  array([ 0.90630779,  0.40821789, -0.10938165]),
#  array([ 0.96342523,  0.24463745, -0.10938165])]

orientation0 = np.array([1, 0, 0])
commands = [(25, 'y'), (75, 'x'), (-10, 'z')]
spaceship_navigation(orientation0, commands)

## Problem 6:
Write a function called `fancy_replacing`, which accepts only one argument called `quadratic_array`. A `quadratic_array` is an arbitrary array of shape `(n, n)`, where `n` is an positive integer.

`fancy_replacing` replaces all values at the borders of `array` with 0 and the diagonal values, but not the values at the border, with 10. 

In [ ]:
# PROBLEM (1)

# SOLUTION
def fancy_replacing(quadratic_array):
    # replace the first and last column with zeros
    quadratic_array[:, [0, -1]] = 0
    # replace the first and last row with zeros
    quadratic_array[[0, -1], :] = 0

    # replace diagonal,  but not at the border
    for i in range(1, quadratic_array.shape[0] - 1):
        quadratic_array[i, i] = 10
    return quadratic_array
# PROBLEM-TEST
fancy_replacing(np.ones((5, 5))).tolist(), fancy_replacing(np.ones((10, 10))).tolist(), fancy_replacing(np.ones((7, 7))).tolist()

In [ ]:
# SELF-CHECK
# the result should be:
# (True,
#  array([[ 0.,  0.,  0.,  0.,  0.],
#         [ 0., 10.,  1.,  1.,  0.],
#         [ 0.,  1., 10.,  1.,  0.],
#         [ 0.,  1.,  1., 10.,  0.],
#         [ 0.,  0.,  0.,  0.,  0.]]))

test_matrix1 = np.ones((5, 5))
fancy_matrix = fancy_replacing(test_matrix1)
isinstance(fancy_matrix, np.ndarray), fancy_matrix